### ISSUE TITLE
EPIC: Pattern Lab Node CLI v1.0

### ISSUE THREAD

**Issue by raphaelokon** [pattern-lab/patternlab-node-cli#32]
- [ ] Update core version to `v3` 
- [x] Switch `wrapAsync()` back to `async/await` (already done in local branch as we started with async/await)
- [x] Update config to latest state
- [x] Write `edition` use case and how to use the CLI within different build tools
